# Built with Jekyll 3.2.0

# Setup
title:               'War Service Bureau'.
tagline:             'personal correspondence from the records of the Rutgers College War Service Bureau'
description:         'A minimal edition using Alex Gil's Ed theme.'
url:                 'http://giannetti.github.io/warservicebureau'
baseurl:             '/warservicebureau'

# About/contact
author:
  name:              Francesca Giannetti
  url:               https://www.libraries.rutgers.edu/profile/francesca_giannetti
  email:             fg162@rutgers.edu

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: red

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


